#!/bin/bash

#Script to determine whether a year is a leap year or not

if [ $# -eq 0 ]; then
echo "Syntax error. Correct syntax: $0 year"
echo "For example: $0 1998"
else
let div1=$1%4
let div2=$1%100
let div3=$1%400
if [ $div1 -eq 0 ]; then
   if [ $div2 -eq 0]; then
      if [ $div3 -eq 0]; then
         echo "$1 is a Leap year"
      else
        echo "$1 is not a Leap year"
      fi
   else
      echo "$1 is a Leap year"
   fi
else
   echo "$1 is not a Leap year"
fi
fi
